# Generated by Django 4.2.6 on 2023-10-12 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
