# Generated by Django 4.2.6 on 2023-10-12 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_user_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
